#!/bin/bash

# pluginname=$(basename $0 .sh)
PLUGINNAME=REPLACELBPPLUGINDIR

echo "DAEMON: Starting DAEMON script" >> $LBPLOG/$PLUGINNAME/ffserver.log
if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$PLUGINNAME - DAEMON Script from $PLUGINNAME Plugin"
fi

# Check if we should start FFServer at boottime
# Source the iniparser
. $LBHOMEDIR/libs/bashlib/iniparser.sh
 
iniparser $LBPCONFIG/$PLUGINNAME/camstream4lox.cfg "FFSERVER"

if [ $FFSERVERSTART -eq 1 ]; then
	echo "DAEMON: Starting FFServer" >> $LBPLOG/$PLUGINNAME/ffserver.log
	if [ -x /usr/bin/logger ]; then
		/usr/bin/logger "loxberry-plugin-$PLUGINNAME - Starting FFServer"
	fi
	# Enable
	$LBHOMEDIR/bin/plugins/$PLUGINNAME/ffserver.sh start > /dev/null 2>&1
fi

# Exit with Status 0
exit 0
